name: app

type: php:8.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: "database:mysql"

hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=22 symfony-build

    deploy: |
        set -x -e
        symfony-deploy
